---
title: "6-Trimming zadanie 6"
output: html_document
date: "2024-11-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Instalacja
```{r} 
install.packages("BiocManager")
library("BiocManager")
```
```{r}
BiocManager::install("ShortRead")
```
```{r}
BiocManager::install("summarised")
```
```{r}

library(ShortRead)
```
## Trimming and filtering
```{r}
fq_reads1 <- readFastq("C:/Users/homer/Downloads/ecoli_simulated1_with_adapters.fq")
fq_reads2 <- readFastq("C:/Users/homer/Downloads/ecoli_simulated2_with_adapters.fq")
```
## Przycinanie
```{r}
quality_symbol <- intToUtf8(33 + 33)
```


```{r}
trimmed_reads1 <- trimTailw(fq_reads1, k = 2, a = "B", halfwidth = 1)
trimmed_reads2 <- trimTailw(fq_reads1, k = 2, a = "B", halfwidth = 1)
trimmed_reads1a <- trimTailw(fq_reads1, k = 3, a = "B", halfwidth = 2)
trimmed_reads2a <- trimTailw(fq_reads1, k = 3, a = "B", halfwidth = 2)
length(fq_reads2)
length(trimmed_reads2)
length(trimmed_reads1)
length(fq_reads1)
length(trimmed_reads1a)
```
```{r}
sum(width(trimmed_reads1) < width(fq_reads1))
sum(width(trimmed_reads2) < width(fq_reads2))
```
# Filtrowanie odczytów forward
```{r}
   filtered_reads1 <- trimmed_reads1[width(trimmed_reads1) >= 50]
```
# Filtrowanie odczytów reverse
  
```{r}
 filtered_reads2 <- trimmed_reads2[width(trimmed_reads2) >= 50]
```
#wyliczanie długości
```{r}
length(filtered_reads1)/length(trimmed_reads1)*100
length(filtered_reads2)/length(trimmed_reads2)*100
```
#Pisaniepliku fastq
```{r}
writeFastq(filtered_reads1,"C:/Users/homer/Downloads/ecoli_simulated1_processed.fq")

```
```{r}
writeFastq(filtered_reads2,"C:/Users/homer/Downloads/ecoli_simulated1_processed2.fq")
```
# Generowanie nowycg raportów QC dla przetworzonych danych:
```{r}
qa_results1 <- qa("C:/Users/homer/Downloads/ecoli_simulated1_with_adapters.fq", type = "fastq")   
qa_results1_processed <- qa( "C:/Users/homer/Downloads/ecoli_simulated1_processed.fq", type = "fastq")
report(qa_results1, dest = "C:/Users/homer/Downloads/QA_report_read1")
report(qa_results1_processed, dest = "C:/Users/homer/Downloads/QA_report_read1_processed")

qa_results2 <- qa("C:/Users/homer/Downloads/ecoli_simulated2_with_adapters.fq", type = "fastq")   
qa_results2_processed <- qa("C:/Users/homer/Downloads/ecoli_simulated1_processed2.fq", type = "fastq")
report(qa_results2, dest = "C:/Users/homer/Downloads/QA_report_read2")
report(qa_results2_processed, dest = "C:/Users/homer/Downloads/QA_report_read2_processed")
```
# Słupkowe wykresy do analizy długościodczytów
```{r}
# Po przycinaniu (forward)
hist(width(fq_reads1), breaks = 50, main = "Długość odczytów forward przez przycinaniem")
# Po przycinaniu (forward)
hist(width(fq_reads2), breaks = 50, main = "Długość odczytów reverse przez przycinaniem")
hist(width(filtered_reads1), breaks = 50, main = "Długość odczytów forward po przycinaniu")
hist(width(filtered_reads2), breaks = 50, main = "Długość odczytów reverse po przycinaniu")

```
```{r}
pdf("C:/Users/homer/Downloads/Hist2.pdf")
hist(width(filtered_reads2), breaks = 50, main = "Długość odczytów reverse po przycinaniu")
dev.off
```

```{r}
BiocManager::install("Biostrings")
library(Biostrings)
   adapter_seq <- DNAString("AGATCGGAAGAGC")
```
# Wykrywanie i usuwanie sekwencji adapterów
```{r}
# Przycinanie adapterów z odczytów forward:
trimmed_reads1_adapt <- trimLRPatterns(
  Lpattern = adapter_seq,
  subject = filtered_reads1
)

# Defuniujemy odczyty po przycięciu adapterów:
filtered_reads1 <- trimmed_reads1_adapt

# Przycinanie adapterów z odczytów reverse:
trimmed_reads2_adapt <- trimLRPatterns(
  Lpattern = adapter_seq,
  subject = filtered_reads2
)

# Defuniujemy odczyty po przycięciu adapterów:
filtered_reads2 <- trimmed_reads2_adapt

```

# sprawdzanie
```{r}
# Porównaj długości przed i po przycięciu adapterów
length(filtered_reads1)
length(trimmed_reads1)

length(filtered_reads2)
length(trimmed_reads2)

# Sprawdź ile odczytów zostało zmodyfikowanych
   sum(width(filtered_reads1) < width(trimmed_reads1))
   sum(width(filtered_reads2) < width(trimmed_reads2))
```
```{r}
paste((length(fq_reads1)-length(trimmed_reads1)/length(fq_reads1)))
```


